### ISSUE TITLE
Use 2019-11-10 d3m core package and latest common-primitives

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil-auto-ml#122]
The latest release of the D3M core package has been released and tagged as `v2019.11.10`.  Distil primitives should migrate to this version.  `common-primitives` has now picked up this version, so we should be using the latest `master` from that project as well.

**Comment by BalazsHoranyi** [comment]
pipeline fixes in https://github.com/uncharted-distil/distil-auto-ml/pull/123

**Comment by cdbethune** [comment]
Given the testing done for ta1 submission, I think this is good now.
