### ISSUE TITLE
Low scores on semi-supervised problems

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil-auto-ml#149]
Our Dec 2019 dry run scores for the various semi-supervised problems are much lower than our July 2019 eval scores.  The data hasn't changed, so changes to the pipelines must have had an adverse impact on performance.

**Comment by BalazsHoranyi** [comment]
This should be fixed by https://github.com/uncharted-distil/distil-auto-ml/pull/147/files.
Reverted back to the old semisupervised pipeline in the router.
