### ISSUE TITLE
Support for min metadata

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil-auto-ml#150]
The new versions of the datasets remove most of the metadata that was supplied in the `datasetDoc.json` file.  We need to be able to infer this type data if there isn't a TA3 that has done so already, or when running stand-alone.

**Comment by BalazsHoranyi** [comment]
approached this by checking the number of column resources vs the number of columns. 
https://github.com/uncharted-distil/distil-auto-ml/compare/feature/min_meta_check.
I feel like there could be a cleaner way, and will need to change if datasetDoc.json gets removed.
