### ISSUE TITLE
Support for multiple pipelines

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil-auto-ml#151]
We currently restrict the system to producing a single pipeline.  This is becoming an issue, as there are cases such as timeseries classification and timeseries forecasting, where different primitives produce much better scores based on a particular dataset and problem.

This work should involve having the search path produce an array of pipelines, sending each back as an individual search result.  A threshold capability won't require those pipelines have any type of ranking or scoring done on them - they just need to be created and returned with a rank that can be arbitrary as a first step.  A TA3 or the eval framework will look after initiating scoring etc.

Proper ranking is a follow on step that will likely brush up against hyper-parameter tuning.

**Comment by BalazsHoranyi** [comment]
Initial work for this: https://github.com/uncharted-distil/distil-auto-ml/pull/152
