### ISSUE TITLE
Scoring target incorrect

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil-auto-ml#22]
The target used in the scoring stage doesn't match what is request by the TA3.  For example, with the baseball data the TA3 can suggest that `home runs` be the target to predict.  It looks like fit/produce stages respect that, but scoring runs on `hall_of_fame` which is the default from the problem file.

**Comment by jbartonthomas** [comment]
@nowfred

**Comment by cdbethune** [comment]
I thought that this was fixed, but I'm seeing it consistently on our internal staging server when running with our TA3.  It looks like what we're using in the pipeline is not the correct target ever - when `SimpleColumnParser` runs, it is pulling the original problem target out.  The D3M runtime used to automatically take the target from the problem and set the semantic type to `TrueTarget` for the appropriate column.  My guess is that's no longer happning, so the `SimpleColumnParser` ends up using the `SuggestedTarget`, which is its last resort.

**Comment by cdbethune** [comment]
Can no longer reproduce in local server, or in our staging server.
