### ISSUE TITLE
Search task looping on cluster

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil-auto-ml#28]
On the cluster we run with an 8 CPU configuration.  There seems to be some type of a race condition that is leading to the exline search task running over and over again.  The fit finishes, it looks like the produce runs, but then it goes back and starts the search again.  This doesn't happen when the CPU count on the cluster is reduced to 2, so its definitely tied to the increased parallelism.

**Comment by cdbethune** [comment]
I added a call to use `StaticPool` during the db engine init and haven't seen the looping issues since.  Not sure if that's a solution, or luck since it was an intermittent issue.

**Comment by nowfred** [comment]
This is probably a partial fix - I think the resolution to #34 should tie this off completely

**Comment by nowfred** [comment]
Closing as have not been able to replicate on a 6core cpu!
