### ISSUE TITLE
Support fully specified pipelines

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil-auto-ml#30]
The system needs to support the execution of fully specified pipelines.  This is the case where a pipeline template is supplied, but the template does not contain the placeholder node.  The search call should immediately return a solution ID, the fit should immediately return a fit ID, and the produce call should result in the pipeline being executed.

**Comment by nowfred** [comment]
G2G

**Comment by cdbethune** [comment]
This doesn't appear to be working.  When a TA3 passes in a pipeline that doesn't contain a inference step it looks like the system follows the standard search path.
