### ISSUE TITLE
Validate against TA3s using CI

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil-auto-ml#92]

**Comment by cdbethune** [comment]
We currently run with our own TA3, but we haven't done any validation against other teams' TA3 systems.

**Comment by waltandrews** [comment]
Currently attempting to run the distil TA2 against the dummy-TA3 in the TA3-TA2 CI interface. This is failing. Tried to upload a newer version of the docker image (the one that was linked in the CI was old) but it is still failing, just a different step.
