### ISSUE TITLE
Binary classification problems failing

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil-auto-ml#94]
We currently don't pass any binary classification datasets due to an issue with the `pos_label` associated with the scoring metric.

Example is 38_sick

**Comment by cdbethune** [comment]
Error needs to be fixed in the ensemble forest primitive.  Only possible work around right now would be to swap that primitive out for the XgBoost as the defaults on that one work reasonably well.

**Comment by BalazsHoranyi** [comment]
potential fix on PR https://github.com/uncharted-distil/distil-primitives/pull/57
