### ISSUE TITLE
Image multiclass problems 

### ISSUE THREAD

**Issue by jbartonthomas** [uncharted-distil/distil-auto-ml#95]
124_174_cifar10 (multiclass classification)
124_214_coil20 (multiclass classification)
124_188_usps (multiclass classification)

**Comment by jbartonthomas** [comment]
These run locally & on the cluster. Waiting for logs from Shelly.

**Comment by jbartonthomas** [comment]
![image](https://user-images.githubusercontent.com/13289537/60928360-ef30f000-a261-11e9-973b-252f125848f8.png)

**Comment by jbartonthomas** [comment]
USPS apparently generates files but these don't upload 

![image](https://user-images.githubusercontent.com/13289537/60929127-e2fa6200-a264-11e9-902c-0de145eab705.png)

**Comment by cdbethune** [comment]
We are going to be allocated more running time for evaluations - program mgmt is still deciding how much that will be so, but I would think that giving us two hours instead of one would be a reasonable increment.  We should expect scores in each of these problems if that's the case, correct?

**Comment by jbartonthomas** [comment]
We should expect scores for USPS if the program increases score time. The
other problems fail in search due to time out.

**Comment by cdbethune** [comment]
Confirmed 3 hours run time which seems sufficient.
